### ISSUE TITLE
Additional mission settings.

### ISSUE THREAD

**Issue by Cam0m1le** [SkaceKamen/random-infantry-skirmish#103]
Thanks for a great mission! My friends and I consider it the best among all PvE missions and spent many hours in it. I would like to see the following features implemented that could improve gameplay:
1. Add a setting to enable revive and drag the body.
2. Add a setting for displaying player names above their heads to make it easier to find your comrades in battle.
3. Add a spawn setting at the initial safe position. Often a situation arises when the enemy kills you a second after spawning into the nearest unit.
4. Add the ability to manually set push points on the map. At the moment, they are not always located well on difficult landscapes.

**Comment by SkaceKamen** [comment]
1. That's not default Arma module right? That has to be a mod? Or is this possible to achieve just with with vanialla arma?
2. Same as (1)
3. So you mean spawn protection? Like player being invincible for the first few seconds after spawning? That should be achievable
4. Yea, I already have this in my head, unfortunately it'll take some time to implement

**Comment by Cam0m1le** [comment]
I will divide it into separate issues
