### ISSUE TITLE
Spawn problems

### ISSUE THREAD

**Issue by Cam0m1le** [SkaceKamen/random-infantry-skirmish#105]
The AI will spawn 20 km from the battle site. There is no one around at certain times.
![20240212234749_1](https://github.com/SkaceKamen/random-infantry-skirmish/assets/122867965/829a6ace-ca1b-4e74-9614-4a2c70af6b10)

**Comment by Cam0m1le** [comment]
The problem does not occur if you disable the option "Spawn new units near group"

**Comment by SkaceKamen** [comment]
Is it happening on MP or SP?

**Comment by Cam0m1le** [comment]
MP, no mods.

**Comment by Cam0m1le** [comment]
My apologies, I checked first in MP and then in SP. The problem occurs only in MP, the parameter "Spawn new units near group" does not matter.

**Comment by SkaceKamen** [comment]
Ok, thanks I'll try to replicate it.

If you pick the soldier in the list, will the camera move to it? Or does it just move to the sea? Do the soldier disappear when you click on Refresh?
Did you try to switch to them?

**Comment by Cam0m1le** [comment]
"Or does it just move to the sea?" - yes. "Do the soldier disappear when you click on Refresh?" -no, he remains on the list. "Did you try to switch to them?" - yes, I find myself at sea.

**Comment by Cam0m1le** [comment]
I suspected something was wrong when I played in the “random unit” spawn mode and found myself in the sea after death. I turned on unit selection mode and saw this problem. I checked it on several computers and on other maps - the same.
