### ISSUE TITLE
Advanced customization screen only works with small interface size.

### ISSUE THREAD

**Issue by mitchdshawn** [SkaceKamen/random-infantry-skirmish#13]
The advanced configuration menu pre-mission isn't displaying correctly, only a small portion of it is visible.
Is this a known issue?  Related to resolution possibly?

Example: http://steamcommunity.com/profiles/76561197963550765/screenshot/924805177049945698

**Comment by mitchdshawn** [comment]
Fixed it: Required interface size to be set to small, normal caused the error.

**Comment by SkaceKamen** [comment]
OK, that shouldn't happen. I'll try to fix it in future.

**Comment by SkaceKamen** [comment]
This should be fixed now
