### ISSUE TITLE
List of multiplayer problems

### ISSUE THREAD

**Issue by Karma1Charger** [SkaceKamen/random-infantry-skirmish#15]
Hey mate. I have found some more issues with the multiplayer

Gunshots cannot be heard. Friend can hear them but its dead silent on my side
No vehicles in the store to buy
respawning ends up putting me on the other team instead of my team

I will add more when we find them. But at the moment. its kinda impossible to play it on coop without sounds

**Comment by SkaceKamen** [comment]
I fixed the issue with vehicle buying and hopefully with the respawning. If you still encounter any issue, please create separate issue for each problem, so it can be easily tracked.
