### ISSUE TITLE
Garbage clean up

### ISSUE THREAD

**Issue by RaiLTC** [SkaceKamen/random-infantry-skirmish#18]
I noticed the bodies don't disappear at all.

After only 5 minutes my FPS went from around 70 to 30, and after another 5 minutes, I barely had 15 FPS.

Garbage collector would be useful. Delete wrecks, disabled vehicles, and bodies.

The mission is fun but would I also suggest custom locations? Fighting in cities requires good hardware. and not to mention it gets boring after a while, so a forest or near the beach would be awesome.

**Comment by SkaceKamen** [comment]
There is garbage collector in mission, you can set the interval in which bodies, disabled vehicles and wrecks get cleaned up in advanced settings.
Do you suspect this cleanup is not actually working? The default interval is 3 minutes for each entity.

**Comment by RaiLTC** [comment]
Yeah, it seems to be not working. Also as another issue is already open, the UI menu is broken.

Would I suggest to change the interval to every 45-60 seconds?

**Comment by SkaceKamen** [comment]
There were some bugfixes in past years so this could be possibly fixed? Feel free to open new issue if not.
