### ISSUE TITLE
Problem with banning vehicles/ weapons

### ISSUE THREAD

**Issue by Optimus1008** [SkaceKamen/random-infantry-skirmish#19]
So, I banned some APCs and some rocket launchers, but at the same time some catagories seem to have disappeared (the weapons tab completely).
I don't know why this is happening, because some days ago everything was fine.

Unsubcribing all of the missions and then subscribing again doesn't seem to fix it.

Here are some images (I don't know if they help):
https://steamcommunity.com/sharedfiles/filedetails/?id=1462868332
https://steamcommunity.com/sharedfiles/filedetails/?id=1462868186

**Comment by SkaceKamen** [comment]
Ok, this is definitely issue, but I can't really see what is causing it without RPT log.
( https://community.bistudio.com/wiki/Crash_Files )

As to how to fix it, resetting settings should do the trick as far as I know. The settings are saved to your profile, so redownloading the mission won't do anything.

**Comment by SkaceKamen** [comment]
Closing this as it's a bit stale and the code behind unit banning was rewritten, feel free to open new issue if this is persisting
