### ISSUE TITLE
can't load any RIS mission from 11/08 update.

### ISSUE THREAD

**Issue by RaikaSiray** [SkaceKamen/random-infantry-skirmish#22]
No mods. Cleaned save data. but can't load it. and can't found Altis version on steam workshop...

**Comment by SkaceKamen** [comment]
Damn, seems like the I44 mod "injected" his dependency to all missions when I was publishing them, despite not being in them at all :-1:

**Comment by RaikaSiray** [comment]
oooh, ok, fine. I'll wait for your work. keep going and good luck.

**Comment by SkaceKamen** [comment]
Ok, I fixed the missions, but the Altis one actually completely disappeared from workshop ... I don't know what happened. I had to republish it, you can find it here:

https://steamcommunity.com/sharedfiles/filedetails/?id=1559969481
