### ISSUE TITLE
base spawn distance

### ISSUE THREAD

**Issue by Dynamo122** [SkaceKamen/random-infantry-skirmish#23]
would it be possible to either add a system for allowing users to pick the distance the AI and Players base spawn from the AO? As it currently stands, the AI and yourself, spawn way too close to the OBJ and this creates chaos. You either get spawn camped by the AI, or your own AI team utterly destroys the enemy AI and then spawn camps their base. If you could increase the distance between the bases/spawns and the AO then this would fix the issue. Even if there was just one OBJ where the distances were further apart then that would be great.

**Comment by SkaceKamen** [comment]
Hi, the base spawn distance is now configurable.
