### ISSUE TITLE
Beketov, Ruha

### ISSUE THREAD

**Issue by caesaravgvstvs** [SkaceKamen/random-infantry-skirmish#28]
mission and customization is amazing! only thing I can suggest is adding Beketov and Ruha maps
beketov - https://steamcommunity.com/sharedfiles/filedetails/?id=743968516
Ruha - https://steamcommunity.com/sharedfiles/filedetails/?id=1368857262

**Comment by SkaceKamen** [comment]
Done https://steamcommunity.com/workshop/filedetails/?id=1376843871
