### ISSUE TITLE
Spawn Issues

### ISSUE THREAD

**Issue by Maurinapoli** [SkaceKamen/random-infantry-skirmish#30]
Hey .. so sometimes the Game wont let me Spawn on the Map.. for example i tried the Wehrmacht 1946 mod on Neaville and Altis.. but iam always stuck in the "Bird view" .. the other Ai units spawn and fight.. 

Happens with other mods too like Nassau or Bope.

**Comment by SkaceKamen** [comment]
Could you please attach the RPT file ( https://community.bistudio.com/wiki/Crash_Files ) of the session when this happens? It should only happen when there's no unit to spawn into.

**Comment by Maurinapoli** [comment]
yep.. here it is.. tried Nassau Mod on Stratis.

https://sharemods.com/eschevaq0y6n/Arma3_x64_2022-04-12_16-10-58.rpt.html

**Comment by SkaceKamen** [comment]
Thanks, I've found the issue and published an update, could you please test if it works now?

**Comment by Maurinapoli** [comment]
yes works now ! 
so you need to update all of the maps right?

**Comment by SkaceKamen** [comment]
All the maps should be updated now :)
