### ISSUE TITLE
Map Request: Weferlingen (Winter); Cham (Summer); Cham (Winter); County Fermanagh, Northern Ireland

### ISSUE THREAD

**Issue by JohnPAB97** [SkaceKamen/random-infantry-skirmish#31]
To add to the collection of GM-based RIS:

Weferlingen (Winter);
Cham (Summer) & Cham (Winter): [https://steamcommunity.com/sharedfiles/filedetails/?id=1789554117](url)
County Fermanagh, Northern Ireland: [https://steamcommunity.com/sharedfiles/filedetails/?id=2626927298](url)

**Comment by SkaceKamen** [comment]
Done https://steamcommunity.com/workshop/filedetails/?id=1376843871
