### ISSUE TITLE
Issuse with a fragmentation of spawning group despite of set value

### ISSUE THREAD

**Issue by bnsonear** [SkaceKamen/random-infantry-skirmish#34]
Hi, SkaceKamen, Thank you for the fantastic mod and your humble listening!

Your mod make me happy, it's my essential mod to play.
Refined push mode with defensive structures delivers more fun to Solo-play of Arma 3.

Here is a report of a bug which has not been fixed since the introduction of new push mode.

Player generally start the mission with 3-3 group. 
If everything is ok, newly spawned unit after death should be designated to the original 3-3 group.

However, the present RIS,  After death of player or friendly AIs, the unit designated to one among 3-3, 3-4, 3-5 and more.
Whether the player is a leader or not, various interactions including calling medical assistant and "taking command" is only available to the unit in the same group. Checking stuck unit (AI) is also crucial, but checking this would be practical when the units are bonded to the same group.
Fragmentation of spawning group could severely decrease the fun of this RIS mod, especially for solo-players.
I miss the perfect unified group for spawning in the old days of Random Infantry Skirmish mod, 
It is really painful to play RIS without AI group support (and ordering)

Of course, "group per side" in Spawning tap has been always 1.
I assumed that "groups advantage" in Enemy tab would induce this bug because I have set the value as +2 (total 3) since the mod install, so I switched it to 0, but the result was the same. BlueFor became fragmented as 3 or more groups.

I prepared a screenshot for comparison. `https://imgur.com/a/X21HxWP`
You can see only one BluFor group in the upper picture, but there are 4 groups in the bottom picture.

Kamen, is it possible that one of my mod spoiled your innocent RIS mod?

Below are a list of my installed mods.
I have got many benefits from the mod and there are many customized settings, so it is not easy to give up mod and disable all of them for test.
However, if you pick up the suspicious mods from the list below, than I will test the gameplay (spawning) with disabling mods you selected.

Thank you for reading this, Kamen.

-----------------------------------------------------------------

3CBBAF Weapons
AbuSayyaf GroupI (NIA)
ace
ACE Compat - RHS GREF
ACE Compat - RHS SAF
ACE Compat - RHSAFRF
ACE Compat - RHSUSAF
ACE compat - RKSL StudiosAttachments3 02
ACE- RHS - CompatibilityPatch for NiArmsComplete
AdvancedRappelling
AdvancedSling Loading
AdvancedUrbanRappelling
AfghanNational ArmyCommandos (SMA)
AfricanSpecialForces (SMA)
AGC-AdvancedGarbageCollector
All-in-OneCommand Menu(Deluxe)
Altiplano
Angola Mapsvl.3
Anizay
Arsenal Search
Australian 2commando and NZSAS [NIA]
AutomaticViewDistance
Beketov
BritishSAS andSBS\ (SMA)
CanadianJoint Task Force2 CANSOF [SMA]
CBA_A3
Central AfricanRebels(NIA)
Chernarus2035
Chernaruswinter With fixed footsteps
CommunityFactionsProject (CFP)
CUPACE3 Compatibility Addon- Weapons
CUPehicles
CUPTerrains- Core
CUPTerrains- CWA
CUPTerrains-Maps
CUPTerrains-Maps
CUPUnits
CUPWeapons
DHI Uniforms andEquipment
DrongosAir Operations
DrongosArtillery
DrongosCommandEnhancement
DrongosMapPopulation
DrongosMissile System
DrongosQuick Respawn
dzn Zeus SearchPatch
EnhancedGPS
EnhancedMapAceversion
EnhancedMovement
EnhancedMovement Rework
EricJTalibanunits
FHQ_Accessories
G.O.S Al Rayak
G.O.S N'ziwasogo
Gorgona
GOSLeskovets
Halsoy.Norway
Hazar-KotValley
Hellanmaa
IntetiorsfotCUP
IslaAbramia
IslaDuala -V
IslandPanthera
Israeli Special Forces Shayetet 13 )SMA)
Jbad
JSRS SOUNDMOD
JSRS SOUNDMOD - CUP WEAPONSMOD SOUNDSUPPORT
JSRS SOUNDMOD - CUPEHICLES MODSOUND SUPPORT
JSRS SOUNDMOD - RHS AFRFMod PackSoundSupport
JSRS SOUNDMOD- RHSUSAFModPack SoundSupport
JSRSSOUNDMOD-ReloadingSounds
JSRSSOUNDMOD-RHSGREFModPackSoundSupport
JSRSSOUNDMOD-RHSSAFMod PackSupport
Kidal
Kujari
Kunduz.Afghanistan
KunduzAfghanistan - Doors& Multiplayer Fix
LAMBS_Danger fsm
Legacy MainMenu (ACEVersion)
lhantala
Limited Gun Movement
Lingor/Dngor Island
LYTHIUM
MAKTACinsignia
MBG Buildings3(Arma2 Legacy)
MBG BuildingsAfricanGeneric (Arma2Legacy)
MCC Sandbox4 Mission MakingTheEasy way
MilitaryGear Pack
MSKE_2017 NA
Mullof Kintyre
NiArms AR15Rifles
NiArms Core
NiArmsAllInOne(VI4 Onwards)
NiArmsFALRifles
NiArmsMG3 GPMGS
NIAtmsAllinOne
NoMoreAircraft Bouncing
Pakistani Special ServiceWing
People’sLiberation Army SpecialForces
PKL LEGACYERSION
PLP Containers
PolishGROMSpecialForces\|RHS\|
Project BLUFOR
Pulau
Ragdoll PhysicsPlus v1.12
ReshmaanProvince
RHSAFRF
RHSGREF
RHSSAF
RHSUSAF
RKSL Studios-Attachments3.02
Rosche Germany
Ruha
Saint Kapaulio
SFFRussianehiclePack
SMA - NIA AmmoPatch
SpecialistMilitaryArms(SMA) version 2.7.1
TF47Launchers
USMARSOCMarineRaiders[NIA]
USMilitaryMod
UzbinValley
VcomAIV3.4
VehicleDoor Actions
VIDDA\|LEGACYERSION
virolahti-Vallatie7
VSM - ACE3 Compatibility
VSM All-In-OneCollection
VT5 -altatie51FinalRelease\|Finnishterrainfor A3
Yellowstone

**Comment by SkaceKamen** [comment]
Hey, thanks for the report, this issue is a complex one.

The mod creates a new group every time new units are spawned, but it's intentional because the AI was very confused when the unit got spawned far away while the rest of the group was on point. They'd either get stuck or wander in random directions.

One solution would be to use something like Battlefield and spawn new units close to the group, but that could lead to balance issues.

**Comment by SkaceKamen** [comment]
Should be deployed soon:
https://github.com/SkaceKamen/random-infantry-skirmish/pull/55

**Comment by SkaceKamen** [comment]
The groups are now reused
