### ISSUE TITLE
Broken map, new map, new functions. 

### ISSUE THREAD

**Issue by Kapotnybanana1858** [SkaceKamen/random-infantry-skirmish#37]
The Vallare bocage map is broken, when you press the play button, nothing happens, it would also be nice to fix the falluja map. it would also be great to add the ability to play defense in push mode. and add more cards straight from the IFA3 mod

**Comment by Kapotnybanana1858** [comment]
@SkaceKamen Where did you disappear to? please don't say that you abandoned this amazing mod :(

**Comment by SkaceKamen** [comment]
@Kapotnybanana1858 Still here, just busy with other stuff :) Maybe I'll find some free time to add more maps and stuff

**Comment by SkaceKamen** [comment]
More IFA3 maps added, see https://steamcommunity.com/workshop/filedetails/?id=1376843871
