### ISSUE TITLE
UI doesn't load.

### ISSUE THREAD

**Issue by NotPurparmalm** [SkaceKamen/random-infantry-skirmish#38]
When I start the scenario, all I see is the sky without any UI.
I use Linux.
I have attached a screenshot of what I see.
The first is just what I see.
The second is with pause menu opened.
![0](https://user-images.githubusercontent.com/106625487/171270561-d59707a3-ef18-4143-bec4-e51e8af1c5bb.png)
![1](https://user-images.githubusercontent.com/106625487/171270571-bd4c114e-b882-4412-806e-46dfaa5e571c.png)
.

**Comment by SkaceKamen** [comment]
Hey could you please try to start the mission and then provide RPT file? See here where to find it: https://community.bistudio.com/wiki/Crash_Files

You can attach it or use https://pastebin.com/

**Comment by Dsarken** [comment]
Same issue here, what could be causing it?

**Comment by TengoPiernas** [comment]
I created a GitHub account just to report this problem, I would like to know if this is currently being planned to be fixed, it´s such a shame that a lot of people cannot play this amazing scenario.

**Comment by SkaceKamen** [comment]
It's usually issue with factions and mods, unless you provide the RPT file I can't tell what's the issue:
> Hey could you please try to start the mission and then provide RPT file? See here where to find it: https://community.bistudio.com/wiki/Crash_Files
> You can attach it here or use https://pastebin.com/

**Comment by SkaceKamen** [comment]
The UI was improved, if the issue persist, feel free to attach the RPT so I can investigate more
