### ISSUE TITLE
**BUG REPORT**

### ISSUE THREAD

**Issue by munzurceza** [SkaceKamen/random-infantry-skirmish#39]
**BUG REPORT:

BUY VEHICLES / SUPPORTS MENU (WINDOWS KEY) NOT OPENING WHEN I LOAD MY SAVED RIS MISSION.

ALSO TEAM DEATHMATCH HUD IS NOT SHOWING WHEN I LOAD MY PREVIUSLY SAVED RIS TDM MISSION.**

**Comment by SkaceKamen** [comment]
Should be fixed now
