### ISSUE TITLE
OPTRE Map request

### ISSUE THREAD

**Issue by K915B** [SkaceKamen/random-infantry-skirmish#52]
Enjoying the mod, I was wondering if you could add the maps from [Operation TREBUCHET](https://steamcommunity.com/sharedfiles/filedetails/?id=769440155), Madrigal, Iberius, and Arcadia.

**Comment by SkaceKamen** [comment]
https://steamcommunity.com/sharedfiles/filedetails/?id=2944181980
https://steamcommunity.com/sharedfiles/filedetails/?id=2946964647
https://steamcommunity.com/sharedfiles/filedetails/?id=2946964680

**Comment by K915B** [comment]
Thanks, it was fun getting to play on these maps. Sorry I think I was wrong, Arcadia might actually it's own map and not part of the main OPTRE mod.
