### ISSUE TITLE
Gliese 581x, Miranda

### ISSUE THREAD

**Issue by Autumn159** [SkaceKamen/random-infantry-skirmish#64]
I was hoping you could add the maps Gliese 581x and Miranda by EAGLE on the Steam workshop please.

Gliese:
https://steamcommunity.com/sharedfiles/filedetails/?id=2397824964

Miranda:
https://steamcommunity.com/sharedfiles/filedetails/?id=2971848020

**Comment by SkaceKamen** [comment]
Published, see https://steamcommunity.com/workshop/filedetails/?id=1376843871
