### ISSUE TITLE
Gameplay issue

### ISSUE THREAD

**Issue by RDSPECTRE** [SkaceKamen/random-infantry-skirmish#65]
![Arma3_x64 2023-11-18 05-38-54-890](https://github.com/SkaceKamen/random-infantry-skirmish/assets/151379639/6f6a866c-8a3f-425a-b9ca-64de410b3d97)
![Arma3_x64 2023-11-18 05-39-21-075](https://github.com/SkaceKamen/random-infantry-skirmish/assets/151379639/04c206dd-c0b1-4419-b3ac-e674fcf1dba7)

**Comment by SkaceKamen** [comment]
Seems to be unrelated to this mission, closing. Feel free to reopen with more info
