### ISSUE TITLE
Units on incorrect Side

### ISSUE THREAD

**Issue by osterizer8** [SkaceKamen/random-infantry-skirmish#66]
Often when playing as INDFOR or OPFOR, some units on your team will become hostile to one another, presumably due to their Side being switched to BLUFOR (or due to the player being switched from BLUFOR) during spawning.

**Comment by SkaceKamen** [comment]
Not sure if there's much I can do about that. I already do my best to switch their side ASAP so this doesn't happen, but for unknown reason this is still an issue sometimes :(
