### ISSUE TITLE
Enemy bots spawn to far away

### ISSUE THREAD

**Issue by wsam06** [SkaceKamen/random-infantry-skirmish#68]
I wish there was a way for the battles to be closer. In some maps the enemy bots are too far away, I wish it were more of Call of duty style, especially for the team deathmatch mode. It makes the gameplay feel slow with the enemy bots being a long distance away, there needs to be a setting in which you can configure the enemy bots' distance.

**Comment by SkaceKamen** [comment]
You can change the spawn distance in the configuration.
