### ISSUE TITLE
VEHICLES NOT SPAWNING IN GAME

### ISSUE THREAD

**Issue by wsam06** [SkaceKamen/random-infantry-skirmish#70]
For me vehicles do not seem to be spawning. I even have vehicles enabled in settings and put 8 vehicles to spawn on each side to the closest unit. When the game starts nothing happens and no vehicles spawn.

**Comment by SkaceKamen** [comment]
AI still has to pay for the vehicles so you'll need to wait for them to earn some money.
If you don't like this mechanic you can set the AI to have a tons of starting money in the configuration.
