### ISSUE TITLE
Conflict with mod "NATO UNIT OVERHAUL"

### ISSUE THREAD

**Issue by acknowledge14** [SkaceKamen/random-infantry-skirmish#79]
HI, I found out that NATO UNIT OVERHAUL is not compatible with RIS missions.
https://steamcommunity.com/workshop/filedetails/?id=1706673977

When test with only this mod loaded, then play any RIS mission, you  find that mission will be stuck in the factions selection screen (3 squares in middle of you screen, but all buttons are unable to click) 
https://steamuserimages-a.akamaihd.net/ugc/975487699575537075/54192FB876F6ADCB8FF0164A6A36AD8EA670B137/

If you press ESC, no menu will be dispalyed, you have to use ALT+F4 to quit Arma3.

So could you please have a look?

**Comment by SkaceKamen** [comment]
You're correct, there's some kind of issue with this mod.
But the not yet released version that I'm currently working on is working fine, so this should be fixed in a few days.

**Comment by acknowledge14** [comment]
> Should be fixed in newest version

HI, I just test using only NATO UNIT OVERHAUL in RIS - Altis 24-2-11 version
https://steamcommunity.com/sharedfiles/filedetails/?id=1559969481&tscn=1708618445
This mod still makes RIS not loading it menu screen, please check it out.
