### ISSUE TITLE
sometimes it takes so long to load in multiplayer

### ISSUE THREAD

**Issue by xKSAx039** [SkaceKamen/random-infantry-skirmish#88]
in sometimes it takes alot of time to load
and also changing maxmium spawn distance will close the menu only fix is to respawn and if you close the respawn menu you will get stuck untill respawn again
and another bug loading so many faction will lead to longer loading and even if you rejoin the scenario after those loadings you still gonna have to wait again 
NVM changing anything in the settings might brake the whole thing i guess making everything load at the same time is causing this

**Comment by SkaceKamen** [comment]
> and also changing maxmium spawn distance will close the menu only fix is to respawn and if you close the respawn menu you will get stuck untill respawn again
Fixed

The loading of factions take some time since the mission is pre-loading info for all of them right now. I think I'll rework it so the factions are only loaded when you're entering the factions config screen or something. Maybe I'd be able to also speed up the loading a bit.

**Comment by SkaceKamen** [comment]
I've pushed an update that should speed up the factions loading time.

**Comment by xKSAx039** [comment]
THANKS SO MUCH
also i listed my ideas in an other thread i hope you like them 😀

**Comment by xKSAx039** [comment]
same issue long loading but its less time then before

**Comment by xKSAx039** [comment]
im not sure but i think the issue is only in multiplayer

**Comment by xKSAx039** [comment]
![image_2024-01-26_194257458](https://github.com/SkaceKamen/random-infantry-skirmish/assets/157706752/0e99969e-e1cc-495a-84b3-e5c35a0e1183)

**Comment by xKSAx039** [comment]
its loading better then before but still not as fast as the old updates please bring what ever in the old update back or tell me what file to preload the factions so i can replace it with the old one

**Comment by SkaceKamen** [comment]
I guess I can close this one too?

**Comment by xKSAx039** [comment]
yeah 

> I guess I can close this one too?
