### ISSUE TITLE
Players in the game do not generate

### ISSUE THREAD

**Issue by ljd12311** [SkaceKamen/random-infantry-skirmish#89]
Setting air carrier and ground carrier limits will result in players not being generated. No mod is used
![Snipaste_2024-01-26_17-42-11](https://github.com/SkaceKamen/random-infantry-skirmish/assets/137818469/6cb724df-47f7-48da-9f61-3cf3402e2a40)

**Comment by SkaceKamen** [comment]
RPT pretty please

**Comment by ljd12311** [comment]
[Arma3_x64_2024-01-29_17-05-35.zip](https://github.com/SkaceKamen/random-infantry-skirmish/files/14082068/Arma3_x64_2024-01-29_17-05-35.zip)

**Comment by SkaceKamen** [comment]
Issue with vehicles spawning, should fixed. Sorry about that.
