### ISSUE TITLE
Lythium Crash

### ISSUE THREAD

**Issue by Savjay-6** [SkaceKamen/random-infantry-skirmish#90]
Upon pressing play for the map Lythium, regardless of mods installed or not it causes the entire game to crash and close to desktop. The scenario wont start under any conditions. After latest updates.

**Comment by SkaceKamen** [comment]
RPT pretty please.

**Comment by Savjay-6** [comment]
[Arma3_x64_2024-01-28_15-42-55.zip](https://github.com/SkaceKamen/random-infantry-skirmish/files/14077657/Arma3_x64_2024-01-28_15-42-55.zip)

**Comment by SkaceKamen** [comment]
Thanks! Seems like some missions were broken by adding the new OPFOR slots. Fix is being pushed right now.

**Comment by SkaceKamen** [comment]
The update should now be pushed. Sorry about that.
