### ISSUE TITLE
is there a way to disable preload factions?

### ISSUE THREAD

**Issue by xKSAx039** [SkaceKamen/random-infantry-skirmish#91]
in old ris it take 30 secs and freezed when you choose a faction now nothing freeze but it takes 3 to 5 mins to load the game due for factions preloading so is there a file i can replace to make it work like the old one?

**Comment by SkaceKamen** [comment]
That weird, it takes ~2 seconds to load ~20 factions. What kind of specs are you running?

**Comment by xKSAx039** [comment]
i5 10400f
GTX 1660
16 GB RAM 

Running 239 mods

> That weird, it takes ~2 seconds to load ~20 factions. What kind of specs are you running?

**Comment by xKSAx039** [comment]
/
![Uploading image_2024-01-28_203943282.png…]()

**Comment by xKSAx039** [comment]
![image_2024-01-28_204001495](https://github.com/SkaceKamen/random-infantry-skirmish/assets/157706752/4f635b76-6ed1-4db4-be29-6d006f789808)

**Comment by SkaceKamen** [comment]
That's a lot of mods, I may try a different loading style.

**Comment by SkaceKamen** [comment]
Can you try now, I've pushed an update that should improve the loading speed significantly for large amounts of factions.

**Comment by xKSAx039** [comment]
> Can you try now, I've pushed an update that should improve the loading speed significantly for large amounts of factions.

sure i try it in zargabad

**Comment by xKSAx039** [comment]
HOLY SHIT ITS WORKING NOW IT LOAD IN LIKE 8 SECS THANK YOU KAMEN YOUR THE BEST KEEP DOING YOUR AMAIZING JOB

**Comment by xKSAx039** [comment]
and sorry for wasting your time for my dumb problem your really great at this make more gamemodes you deserve more pepole

**Comment by SkaceKamen** [comment]
Glad it's resolved now 👍
